# Generated by Django 3.2.9 on 2022-06-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesdetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/Places'),
        ),
        migrations.AddField(
            model_name='placesdetails',
            name='seasion_to_visite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
