# Generated by Django 3.2.9 on 2022-06-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_placesdetails_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placesdetails',
            old_name='seasion_to_visite',
            new_name='month_to_visit',
        ),
    ]
