# Generated by Django 3.2.9 on 2022-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_rename_seasion_to_visite_placesdetails_month_to_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesdetails',
            name='day_open',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
