# Generated by Django 3.2.9 on 2022-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0006_auto_20220625_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesdetails',
            name='avg_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placesdetails',
            name='avg_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placesdetails',
            name='morality_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placesdetails',
            name='petroling_vans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placesdetails',
            name='police_station_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placesdetails',
            name='population_density',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
