# Generated by Django 3.2.9 on 2022-07-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0007_complaintsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsdata',
            name='name_of_place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
