# Generated by Django 3.2.9 on 2022-09-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0007_auto_20220717_0118'),
        ('Places', '0008_alter_complaintsdata_name_of_place'),
    ]

    operations = [
    ]
