# Generated by Django 3.2.9 on 2022-07-17 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0009_merge_20220717_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintsdata',
            old_name='complaints',
            new_name='complaints_desc',
        ),
        migrations.AddField(
            model_name='complaintsdata',
            name='complaint_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='complaintsdata',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintsdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 1), ('SUCCESS', 2)], default=1, max_length=100),
        ),
    ]
