# Generated by Django 3.2.9 on 2022-07-18 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Places', '0010_auto_20220717_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety', models.CharField(blank=True, choices=[('VERY_POOR', 1), ('POOR', 2), ('MEDIOCRE', 3), ('GOOD', 4), ('EXCELLENT', 5)], max_length=100)),
                ('sanitization', models.CharField(blank=True, choices=[('VERY_POOR', 1), ('POOR', 2), ('MEDIOCRE', 3), ('GOOD', 4), ('EXCELLENT', 5)], max_length=100)),
                ('security', models.CharField(blank=True, choices=[('VERY_POOR', 1), ('POOR', 2), ('MEDIOCRE', 3), ('GOOD', 4), ('EXCELLENT', 5)], max_length=100)),
                ('overall_fun', models.CharField(blank=True, choices=[('VERY_POOR', 1), ('POOR', 2), ('MEDIOCRE', 3), ('GOOD', 4), ('EXCELLENT', 5)], max_length=100)),
                ('review', models.TextField(default='Awesome')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.placesdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
