# Generated by Django 3.2.9 on 2023-10-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='issue',
            new_name='post',
        ),
    ]
