# Generated by Django 3.2.9 on 2022-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_visitordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordetails',
            name='gender',
            field=models.CharField(default='Female', max_length=20),
        ),
    ]
