# Generated by Django 3.2.9 on 2022-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_visitordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordetails',
            name='sos_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
