# Generated by Django 3.2.9 on 2022-07-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0003_visitordetails_gender'),
        ('Visitor', '0003_visitordetails_sos_contact'),
    ]

    operations = [
    ]
