# Generated by Django 3.2.9 on 2022-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0004_merge_20220717_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 1), ('FEMALE', 2)], default=1, max_length=20),
        ),
    ]
