# Generated by Django 3.2.9 on 2022-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0005_alter_visitordetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordetails',
            name='gender',
            field=models.CharField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'TRANSGENDER')], default=1, max_length=20),
        ),
    ]
