# Generated by Django 3.2.9 on 2022-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0006_alter_visitordetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 0), ('FEMALE', 1), ('TRANSGENDER', 2)], default=1, max_length=20),
        ),
    ]
