# Generated by Django 3.2.9 on 2022-10-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0007_alter_visitordetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordetails',
            name='profile_picture',
            field=models.ImageField(default='media/images/Visitors/default.jpg', upload_to='media/images/Visitors/'),
        ),
    ]
