# Generated by Django 3.2.9 on 2023-10-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0011_alter_visitordetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default=1, max_length=20),
        ),
    ]
